### PR TITLE
fix: comply with original HTTP API by disabling AbortControlle by defeault

### LINKED ISSUE #6: API incompatibility with meteor/http default timeout
Hi,

I am not sure if the library is still maintained. We used this to migrate to latest meteor in our projects without changing much syntax for http calls except the http timeout setting.

With the Abort Controller implementation in this library, the default timeout is set to 90s.
But, the original meteor/http library does not have a default timeout at all.
Refer - https://docs.meteor.com/api/http.html#HTTP-call

> timeout Number
Maximum time in milliseconds to wait for the request before failing. There is no timeout by default.

Please update this in the docs regd. preserving original API functionality, or remove the default timeout setting.

Thanks!

### PR DESCRIPTION
**Pull request by jankapunkt**
Disabled AbortController by default by setting the defualt timeout value to -1 and only include AbortController if the timeout is greater than -1

### CODE REVIEW

File: httpcall_server.js [hunk 1]
```diff
@@ -166,9 +181,7 @@ function _call (method, url, options, callback) {
       }
     })
     .catch(err => callback(err))
-    .finally(() => {
-      clearTimeout(timeoutId)
-    })
+    .finally(() => clearTimeout(timeoutId))
```
Comment (sree-qlp) [inline httpcall_server.js]: a small thing here - `timeoutId` exists only if `useAbort` is true

**Review by sree-qlp — APPROVED** [review]
Thanks a lot @jankapunkt 
Looks great!
